### ISSUE TITLE
运行leveldb.js，报错

### ISSUE THREAD

**Issue by ichunhui** [fanpei91/torsniff#50]
你好！运行leveldb.js，程序报错，如下，nodejs：0.12.13。求解答

> [root@iZ2848wc4tlZ p2p]# node samples/leveldb.js 
> /root/p2p/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:83
>         throw e
>               ^
> Error: /root/p2p/node_modules/level/node_modules/leveldown/build/Release/leveldown.node: ELF load command past end of file
>     at Error (native)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at bindings (/root/p2p/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
>     at Object.<anonymous> (/root/p2p/node_modules/level/node_modules/leveldown/leveldown.js:4:46)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)

**Comment by Fuck-You-GFW** [comment]
@sean-liang Your customer is here. :)
