### ISSUE TITLE
不知道这样运行对不对?

### ISSUE THREAD

**Issue by apersonlikesc** [fanpei91/torsniff#67]
我把release 的package下载下来
chmod +x  packagename然后 就 nohup ./packagename&

之后就没动静了...
就只有一句话的输出 running, it may take a few minutes...

有没有什么地方有错的?之后大概需要等待几天时间会有结果出现

**Comment by fanpei91** [comment]
那就说明有网络问题：你在没有端口映射的内网环境运行，或许是被防火墙给屏蔽了，或许是这样那样我都不知道都环境运行。

简单粗暴点，在 vultr 搞台最便宜的，装上最新的 ubuntu 来运行 torsniff，不出一分钟，你就惊喜了。我只在 vultr 上运行过，没在其他环境地方过。

**Comment by apersonlikesc** [comment]
我用的是阿里云的ubuntu服务器,已经把6881的udp端口开了 -.- 
我连home下的torrents都没出现 -.-

**Comment by fanpei91** [comment]
放在国外，就好使了，国内这网络环境，莫名其妙的。

**Comment by apersonlikesc** [comment]
可怕的长城....
