### ISSUE TITLE
为什么从js改成了go.看issues半天，看的我一脸懵逼。

### ISSUE THREAD

**Issue by kkshsh** [fanpei91/torsniff#73]
想知道是因为什么换了语言，node效率不行吗？

**Comment by fanpei91** [comment]
最主要是以我的能力，写出的 node 代码不好读，所以就不好维护。

**Comment by fanpei91** [comment]
@iugo 如果一门编程能让你更快更好地从其他优秀的开源代码学习，它就是一门好语言，它能让你更快进步。

Go 对我来说就是这样的编程语言，只要我感兴趣的开源项目，都比较容易读懂。最近我在深入读的开源项目是 [netstack](https://github.com/google/netstack)，很好读。进步了许多，对 TCP  有了非常的深入的理解，也自己基于 UDP 写了个可靠的传输协议，等几天会开源一个用了此传输协议的工具出来。敬请期待。：）

**Comment by kkshsh** [comment]
我是这个项目才接触go，我现在把数据存到mysql数据库里。偶尔会报错，
Error 1366: Incorrect string value: '\xAA\xD8\xB4\xB7\xD5\xE8...' for column 'title' at row 1
Error 1366: Incorrect string value: '\xCC\xE0\xF2\xF7 \xCF...' for column 'title' at row 1
数据库的字符是 utf8mb4_general_ci 。
我把这些转义成字符串也是“����”看不懂的字符。
现在我想判断一下如果是无法存储的字符就删掉，有没有现成的代码可以抄一抄。
