### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by monkey000** [fanpei91/torsniff#74]
用torsniff -p 8899启动后，终端已经开始显示种子信息了
curl 127.0.0.1:8899还是提示curl: (7) Failed to connect to 127.0.0.1 port 8899: Connection refused

**Comment by fanpei91** [comment]
-p 选项是 UDP 协议，curl 是走 TCP 协议，所以连不上。

**Comment by monkey000** [comment]
正常的使用流程是什么？
如何搜索？
在浏览器用ip:端口打开前端页面？
还是单纯的在后台将种子下载到指定目录？

**Comment by fanpei91** [comment]
单纯地在后台将种子下载到指定目录。要做搜索，自己去改代码。
