### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by jiaqiyu543** [fanpei91/torsniff#78]
我先是下载工具  wget https://github.com/fanpei91/torsniff/releases/download/v0.1.0/torsniff-v0.1.0-linux-amd64
torsniff-v0.1.0-linux-amd64  字体是白色的 
运行 sudo ./torsniff-v0.1.0-linux-amd64   
报错  sudo: ./torsniff-v0.1.0-linux-amd64: command not found  
请问这是什么原因

**Comment by fanpei91** [comment]
```chmod +x torsniff-v0.1.0-linux-amd64```

**Comment by jiaqiyu543** [comment]
thank you very much   




------------------ 原始邮件 ------------------
发件人: "fanpei91"<notifications@github.com>; 
发送时间: 2019年4月27日(星期六) 下午3:23
收件人: "fanpei91/torsniff"<torsniff@noreply.github.com>; 
抄送: "854013212"<854013212@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fanpei91/torsniff] 无法运行 (#78)




chmod +x torsniff-v0.1.0-linux-amd64

**Comment by jiaqiyu543** [comment]
ok   很抱歉 我这个新手给您带来麻烦了




------------------ 原始邮件 ------------------
发件人: "fanpei91"<notifications@github.com>; 
发送时间: 2019年4月27日(星期六) 下午3:27
收件人: "fanpei91/torsniff"<torsniff@noreply.github.com>; 
抄送: "854013212"<854013212@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fanpei91/torsniff] 无法运行 (#78)




Closed #78.

**Comment by fanpei91** [comment]
没事，有人提 issue，我很高兴的，说明有人在用，有人反馈，没那么孤单。

**Comment by jiaqiyu543** [comment]
哈哈  司机的路上并不孤独

**Comment by fanpei91** [comment]
我已经玩腻了都，好几年不玩了，你要是有什么新玩法，可以分享下。

**Comment by jiaqiyu543** [comment]
好的   




------------------ 原始邮件 ------------------
发件人: "fanpei91"<notifications@github.com>; 
发送时间: 2019年4月27日(星期六) 下午3:35
收件人: "fanpei91/torsniff"<torsniff@noreply.github.com>; 
抄送: "854013212"<854013212@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fanpei91/torsniff] 无法运行 (#78)




我已经玩腻了都，好几年不玩了，你要是有什么新玩法，可以分享下。

**Comment by daimiaopeng** [comment]
段错误???
