### ISSUE TITLE
你好，下载了最新版linux,怎么用呢

### ISSUE THREAD

**Issue by HALF-MAN** [fanpei91/torsniff#79]
release里的包是什么格式的，需要安装吗，./torsniff -h  不好使，提示
VM_0_15_centos ~]$ ./torsniff -h
-bash: ./torsniff: No such file or directory

**Comment by fanpei91** [comment]
`chmod +x torsniff`

**Comment by HALF-MAN** [comment]
haha, im so stupid...它开始工作了，非常感谢
