### ISSUE TITLE
tracker地址能自己换吗？

### ISSUE THREAD

**Issue by prodcd** [fanpei91/torsniff#83]
我在https://github.com/ngosang/trackerslist看到的tracker地址，和dht.go的seeds[]里的地址不太一样，不知道怎样换。现在软件启动后长时间没反应，感觉是连接tracker的事。

**Comment by fanpei91** [comment]
目前是  hard code, 你可直接自己替换再编译即可。

**Comment by fanpei91** [comment]
我看了下，这些 tracker 不是 dht seeder。你没法替换。你的问题很可能是因为网络问题、防火墙问题。

一般来说，我懒得给你排除你那里环境问题。所以我直接一股脑儿推荐用 vultr， https://www.vultr.com/?ref=7172229

选用 ubuntu 操作系统，一切都搞定了。

**Comment by prodcd** [comment]
好吧，看来是我把一些概念搞混了。是网络问题，也许几分钟能连上，也许几个小时。目前平均每秒能拿到一个种子。
