### ISSUE TITLE
建议增加一个统计，监控爬虫运行情况

### ISSUE THREAD

**Issue by hyqhyq3** [fanpei91/torsniff#9]
建议每隔几秒输出一个日志，要不然也不知道爬虫在干啥

接收annonce数： 100/s
活跃连接数： 20
获得metadata数: 20/s
总metadata叔: 3000

**Comment by Fuck-You-GFW** [comment]
这个可以有. 使用者传一个回调函数, 爬虫把信息传给此回调函数, 使用者根据自己的需要对此信息处理.

**Comment by Fuck-You-GFW** [comment]
这代码最好写成能让用户像如下方式使用:
```js
p2p.on('status', function(status) {
    // do something
})
```

**Comment by 4405531** [comment]
有了吗
